config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
  }
  root   'static_pages#home'
  get    '/home',    to: 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/terms',   to: 'static_pages#terms'
  get    '/contact', to: 'static_pages#contact'
  get    '/users',   to: 'application#back_root'
  get    '/trips',   to: 'application#back_root'
  get    '/memos',   to: 'application#back_root'

  resources :trips, expect: [:index] do
    member do
      patch :destroy_image
    end
  end
  resources :memos, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates  :user_id, presence: true
  validates  :content, length: { maximum: 200 }
  validates  :content_or_address, presence: true

  private

  def content_or_address
    content.presence || address.presence
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates  :user_id,    presence: true
  validates  :title,      presence: true,
                          length: { maximum: 100 }
  validates  :content, length: { maximum: 200 }
  validates  :images, content_type: { in: %w(image/jpeg image/gif image/png) }

  def top_image
    if images.attached?
      images.first.variant(resize_to_fill: [320, 320])
    else
      "default.jpg"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :timeoutable, :trackable

  validates :name, presence: true,
                   length: { maximum: 50 }

  has_many :trips
  has_many :memos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end

  def back_root
    redirect_to root_url
  end

  private

  def sign_in_required
    redirect_to new_user_session_url unless user_signed_in?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]

  def new
    @memo = current_user.memos.build
    @memos = current_user.memos.order("created_at DESC").
      paginate(page: params[:page])
  end

  def create
    @memo = current_user.memos.build(memo_params)
    @memos = current_user.memos.paginate(page: params[:page])
    if @memo.save
      flash[:success] = "メモを追加しました"
      redirect_to new_memo_path
    else
      render 'new'
    end
  end

  def destroy
    Memo.find(params[:id]).destroy
    flash[:success] = "メモを消去しました"
    redirect_to new_memo_path
  end

  private

  def memo_params
    params.require(:memo).permit(:content, :address)
  end

  def correct_user
    @memo = current_user.memos.find_by(id: params[:id])
    redirect_to root_url if @memo.nil?
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      if params[:title].present?
        @trips = Trip.where('title LIKE ?', "%#{params[:title]}%").
          or(Trip.where('address LIKE ?', "%#{params[:title]}%")).
          and(Trip.where(user_id: current_user.id)).
          order("created_at DESC").
          paginate(page: params[:page], per_page: 9)
      else
        @trips = Trip.where(user_id: current_user.id).
          order("created_at DESC").
          paginate(page: params[:page], per_page: 9)
      end
      render 'login_home'
    else
      render 'logout_home', layout: false
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  def terms
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :update, :destroy_image, :destroy]

  def show
    @trip = Trip.find(params[:id])
    @images = @trip.images.order("created_at DESC").
      paginate(page: params[:page], per_page: 9)
  end

  def new
    @trip = current_user.trips.build
  end

  def create
    @trip = current_user.trips.build(trip_params)
    if @trip.save
      flash[:success] = "作成しました。"
      redirect_to @trip
    else
      render 'new'
    end
  end

  def update
    @trip = current_user.trips.find_by(id: params[:id])
    attach_images(@trip)
    update_contents(@trip)
  end

  def destroy_image
    @trip = current_user.trips.find_by(id: params[:id])
    if params[:trip] && params[:trip][:image_ids]
      params[:trip][:image_ids].each do |image_id|
        image = @trip.images.find(image_id)
        image.destroy
      end
      flash[:success] = "写真を削除しました。"
      redirect_to(@trip) && return
    end
    flash[:danger] = "削除する写真を選択してください。"
    redirect_to @trip
  end

  def destroy
    Trip.find(params[:id]).destroy
    flash[:success] = "旅行を削除しました"
    redirect_to root_path
  end

  private

  def trip_params
    params.require(:trip).permit(:title, :content, :address)
  end

  def correct_user
    @trip = current_user.trips.find_by(id: params[:id])
    redirect_to root_url if @trip.nil?
  end

  def attach_images(trip)
    if params[:trip][:images].present?
      unless trip.images.attach(params[:trip][:images])
        flash[:danger] = "有効な画像形式にしてください。"
        redirect_to trip
      end
    end
  end

  def update_contents(trip)
    if trip.update(trip_params)
      flash[:success] = "内容を変更しました。"
      redirect_to trip
    else
      flash[:danger] = "100文字以内のタイトルを入力してください。"
      redirect_to trip
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    if page_title.blank?
      "TABISORA"
    else
      "#{page_title} | TABISORA"
    end
  end
end

app/views/layouts/_alert.html.erb
<% if notice.present? %>
  <div class="alert">
    <div class="alert alert-success"><%= notice %></div>
  </div>
<% elsif alert.present? %>
  <div class="alert">
    <div class="alert alert-danger"><%= alert %></div>
  </div>
<% end %>
<% flash.each do |message_type, message| %>
  <% if message != notice %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "利用規約", terms_path %></li>
      <li><%= link_to "よくある質問", help_path %></li>
      <li><%= link_to "お問合せ", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <%= link_to "tabisora", root_path, id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to "ホーム", root_path %>
      </li>
      <% if user_signed_in? %>
        <%= render'layouts/header_login' %>
      <% else %>
        <%= render'layouts/header_logout' %>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_header_login.html.erb
<li class="nav-item">
  <%= link_to '旅行ページ作成', new_trip_path %>
</li>
<li class="nav-item">
  <%= link_to 'メモ', new_memo_path %>
</li>
<li class="nav-item">
  <%= link_to 'ユーザー編集', edit_user_registration_path %>
</li>
<li class="nav-item">
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
</li>

app/views/layouts/_header_logout.html.erb
<li class="nav-item">
  <%= link_to '旅空とは？', about_path %>
</li>
<li class="nav-item">
  <%= link_to '新規登録', new_user_registration_path %>
</li>
<li class="nav-item">
  <%= link_to 'ログイン', new_user_session_path %>
</li>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/alert' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/memos/_large_map.html.erb
<script type="text/javascript">
  function initMap() {
    var test ={lat: 39, lng: 138};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 5,
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    <% objects.each do |object| %>
      <% if object.address.present? || object.latitude.present? || object.longitude.present? %>
        var contentString = '<%= object.address %>';
        var locate ={lat: <%= object.latitude %>, lng: <%= object.longitude %>};
        var marker = new google.maps.Marker({
                     position: locate,
                     map: map,
                     title: contentString
                   });
       <% end %>
     <% end %>
  }
</script>
<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>

app/views/memos/_memo.html.erb
<li>
  <div class="memo">
    <%= memo.address %>
    <%=simple_format(memo.content)%>
    <div class="delete">
      <%= link_to "削除", memo, method: :delete,
          data: { confirm: "本当に削除しても、よろしいでしょうか？" } %>
    </div>
  </div>
</li>

app/views/memos/new.html.erb
<% provide(:title, "メモ") %>

<h1>次はどこに行こう？</h1>

<div class="large-map">
  <div id="map"></div>
</div>

<div class="form-open">
  <%= link_to "Google マップへ移動する", 'https://www.google.co.jp/maps',
              class: "btn btn-lg btn-success", target: "_blank", rel: "noopener noreferrer" %>
  <button class="btn btn-primary btn-lg">メモを追加</button>
</div>

<div class="form-box">
  <%= form_with(model: @memo, remote: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :adress, "旅行先" %>
    <%= f.text_field :address, placeholder: "旅行先を記入することができます..." %>
    <%= f.label :content, "内容" %>
    <%= f.text_area :content, placeholder: "メモの内容を記入することができます..." %>
    <%= f.submit "メモを追加", class: "btn btn-primary btn-lg",
                   data: { confirm: "メモの内容に間違いはありませんか？" } %>
  <% end %>

  <div class="form-close">
    <button class="btn btn-lg">閉じる</button>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h3>
      メモ(<%= @memos.count %>)
    </h3>
    <% if @memos.any? %>
      <ul class="memos">
        <%= render @memos %>
      </ul>
        <%= will_paginate @memos %>
    <% else %>
    <h2>
      行きたい場所のメモを追加しよう
    </h2>
    <% end %>
  </div>
</div>

<%= render 'large_map', objects: @memos %>
<%= javascript_pack_tag 'shared/form' %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力内容には<%= object.errors.count %>個のエラーがあります
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_example.html.erb
<div class="example">
  ログインより、以下のサンプルユーザーにログインできます
  <p></p>
  <ul>
    <li class="name"><strong>Example User</strong></li>
    <li>メールアドレス: example@user.org</li>
    <li>パスワード: foobar</li>
    <p></p>
    <li class="name"><strong>Another User</strong></li>
    <li>メールアドレス: another@user.org</li>
    <li>パスワード: hogehoge</li>
    <div class="relation">
      <strong>関連サービス</strong>
      <p><%= link_to "・SharePhoto", "https://mysterious-headland-92680.herokuapp.com/",
                             target: "_blank", rel: "noopener noreferrer" %></p>
    </div>
  </ul>
</div>

app/views/shared/_large_map.html.erb
<script type="text/javascript">
  function initMap() {
    var test ={lat: 39, lng: 138};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 5,
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var style = [{
    featureType: 'all',
    elementType: 'labels',
    stylers: [{ visibility: 'off' }]
    }];
    var lopanType = new google.maps.StyledMapType(style);
    map.mapTypes.set('noText', lopanType);
    map.setMapTypeId('noText');

    <% objects.each do |object| %>
      <% if object.address.present? || object.latitude.present? || object.longitude.present? %>
        var contentString = '<%= object.address %>';
        var locate ={lat: <%= object.latitude %>, lng: <%= object.longitude %>};
        var marker = new google.maps.Marker({
                     position: locate,
                     map: map,
                     title: contentString
                   });
       <% end %>
     <% end %>
  }
</script>
<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>

app/views/static_pages/_large_map.html.erb
<script type="text/javascript">
  function initMap() {
    var test ={lat: 39, lng: 138};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 5,
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var style = [{
    featureType: 'all',
    elementType: 'labels',
    stylers: [{ visibility: 'off' }]
    }];
    var lopanType = new google.maps.StyledMapType(style);
    map.mapTypes.set('noText', lopanType);
    map.setMapTypeId('noText');

    <% objects.each do |object| %>
      <% if object.address.present? || object.latitude.present? || object.longitude.present? %>
        var contentString = '<%= object.address %>';
        var locate ={lat: <%= object.latitude %>, lng: <%= object.longitude %>};
        var marker = new google.maps.Marker({
                     position: locate,
                     map: map,
                     title: contentString
                   });

        marker.addListener('click', function() {
          location.href= '<%= trip_path(object.id) %>';
        });
       <% end %>
     <% end %>
  }
</script>
<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>

app/views/static_pages/_login_home.html.erb
<div class="large-map">
  <div id="map"></div>
</div>

<div class="row">

  <div class="col-md-6 col-md-offset-3">
    <% unless @trips.present? %>
      <div class="no-trips">
        <h2>
          旅行ページがありません。
          <p>新規作成して、写真を管理することができます。</p>
        </h2>
        <%= link_to '旅行を作成する', new_trip_path, class: "btn btn-lg btn-success btn-new" %>
      </div>
    <% end %>

    <%= form_with url: root_path, method: :get, local: true do |f| %>
      <%= f.text_field :title, placeholder: "タイトルや旅行先から、旅行を検索できます..." %>
      <%= f.submit "検索", class: "btn btn-lg btn-primary btn-search" %>
    <% end %>
  </div>
</div>
<h3 class = "trips-count">
  (<%= @trips.count %>)
</h3>
<div class="trips">
  <%= render @trips %>
</div>

<div class="pagination-box">
  <%= will_paginate @trips %>
</div>

<%= render 'shared/large_map', objects: @trips %>

app/views/static_pages/about.html.erb
<% provide(:title, "旅空とは？") %>

<div class="center jumbotron">
  <div class="content">
    <h1>旅空とは？</h1>
    <h3>
      ようこそ、旅空へ！
      <p>旅空は、旅行写真の管理サービスです！</p>
      <p>①行きたい場所のメモを作成！</p>
      <%= image_tag 'about-image.png' %>
      <p>②個別ページを作って、写真と旅行先を追加！</p>
      <%= image_tag 'about-image2.png' %>
      <p>③たくさんの旅行写真を管理できます！</p>
      <%= image_tag 'about-image3.png' %>
    </h3>
    <%= link_to "旅空を始める", new_user_registration_path, class: "btn btn-lg btn-success" %>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "お問合せ") %>
<h1>お問合せ</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "よくある質問") %>
<h1>よくある質問</h1>

app/views/static_pages/login_home.html.erb
<div class="large-map">
  <div id="map"></div>
</div>

<div class="row">

  <div class="col-md-6 col-md-offset-3">
    <% unless @trips.present? %>
      <div class="no-trips">
        <h2>
          旅行ページがありません。
          <p>新規作成して、写真を管理することができます。</p>
        </h2>
        <%= link_to '旅行を作成する', new_trip_path, class: "btn btn-lg btn-success btn-new" %>
      </div>
    <% end %>

    <%= form_with url: root_path, method: :get, local: true do |f| %>
      <%= f.text_field :title, placeholder: "タイトルや旅行先から、旅行を検索できます..." %>
      <%= f.submit "検索", class: "btn btn-lg btn-primary btn-search" %>
    <% end %>
  </div>
</div>
<h3 class = "trips-count">
  (<%= @trips.count %>)
</h3>
<div class="trips">
  <%= render @trips %>
</div>

<div class="pagination-box">
  <%= will_paginate @trips %>
</div>

<%= render 'large_map', objects: @trips %>

app/views/static_pages/logout_home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="logout-home">
      <%= render 'layouts/alert' %>
      <div class="center">
        <div class="content">
          <h1>旅空</h1>
          <h3>
            ようこそ、旅空へ！
            <p>旅空は、旅行写真の管理サービスです！</p>
          </h3>
          <p><%= link_to "旅空とは？", about_path, class: "btn btn-lg btn-success" %></p>
          <p><%= link_to "ログイン", new_user_session_path, class: "btn btn-lg btn-success" %></p>
          <p><%= link_to "新規登録", new_user_registration_path, class: "btn btn-lg btn-success" %></p>
          <%= render 'shared/example' %>
        </div>
      </div>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<h1>利用規約</h1>

app/views/trips/_detail_map.html.erb
<script type="text/javascript">
  function initMap() {
    var test ={lat: <%= trip.latitude %>, lng: <%= trip.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 10,
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= trip.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
                  position: test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>

<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>

app/views/trips/_modal.html.erb
<div class="modal modal-change modal-close" id="Modal-<%= image.id %>" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true" data-dismiss="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body" data-dismiss="modal">
        <%= image_tag(image) %>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'trips/modal' %>

app/views/trips/_trip.html.erb
<button class="garally" id="trip-<%= trip.id %>">
  <%= link_to trip do %>
    <span class="garally-title"><%= trip.title %></span>
    <%= image_tag trip.top_image, alt: "trip-image" %>
  <% end %>
</button>

app/views/trips/new.html.erb
<% provide(:title, '旅行作成') %>

<h1>旅行作成</h1>
<div class="title">
  新たに旅行のページを作成できます。
</div>

<%= form_with(model: @trip, remote: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title, "タイトル" %>(必須)
  <%= f.text_field :title, placeholder: "タイトルを記入してください..." %>
  <%= f.label :content, "コメント" %>
  <%= f.text_area :content, placeholder: "コメントを記入することができます..." %>
  <%= f.label :adress, "旅行先" %>
  <%= f.text_field :address, placeholder: "旅行先を記入することができます..." %>
  <%= f.submit "旅行作成", class: "btn btn-primary btn-lg",
        data: { confirm: "投稿の内容に間違いはありませんか？" } %>
  <%= f.submit "リセット", type: :reset ,class: "reset btn btn-lg btn-warning" %>
<% end %>

app/views/trips/show.html.erb
<% provide(:title, @trip.title) %>

<div class="title">
  <strong><%= @trip.title %></strong>
</div>
<% if @trip.address.present? || @trip.latitude.present? || @trip.longitude.present? %>
  <div class="detail-map">
    <div id="map"></div>
  </div>
<% end %>

<div class="content">
  <% if @trip.content.present? %>
    <%= simple_format(@trip.content) %>
  <% else %>
    <h2>
      「編集する」より、コメントを追加することができます。
    </h2>
  <% end %>
</div>

<div class="form-open">
  <button class="btn btn-primary btn-lg">編集する</button>
</div>

<div class="form-box">
  <%= form_with(model: @trip, remote: true) do |f| %>

    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, placeholder: "タイトルをを記入してください..." %>
    <%= f.label :content, "コメント" %>
    <%= f.text_area :content, placeholder: "コメントを記入することができます..." %>
    <%= f.label :adress, "旅行先" %>
    <%= f.text_field :address, placeholder: "旅行先を記入することができます..." %>
    <%= f.label :images, "写真を追加" %>
    <%= f.file_field :images, multiple: true, accept: "image/jpeg,image/png" %>
    <%= f.submit "変更する", class: "btn btn-primary btn-lg",
          data: { confirm: "変更する内容に間違いはありませんか？" } %>
    <%= f.submit "変更内容をリセット", type: :reset ,class: "reset btn btn-lg btn-warning" %>
  <% end %>

  <%= link_to "この旅行を削除", @trip, method: :delete, class: "btn btn-danger btn-lg",
                              data: { confirm: "本当に削除しても、よろしいでしょうか？" } %>

  <div class="form-close">
    <button class="btn btn-lg">閉じる</button>
  </div>
</div>

<% if @images.present? %>
  <%= form_with(model: @trip, url: {controller: 'trips', action: 'destroy_image'} , remote: true) do |f| %>

    <div class="photo-delete-form">
      <div class="btn btn-danger btn-lg">写真を削除</div>
    </div>

    <div class="photo-delete-btn">
      <div class="btn btn-warning btn-lg photo-reset-btn">削除取り消し</div>
      <%= f.submit "写真を削除", class: "btn btn-danger btn-lg",
                                data: { confirm: "本当に削除しても、よろしいでしょうか？" } %>
      <div class="title">
        削除する写真を、チェックボックスより選択してください。
      </div>
    </div>

    <h3 class="trips-count">
      写真(<%= @images.count %>)
    </h3>
    <div class="trips">
      <% @images.each do |image| %>
        <div class="garally" id="image-<%= image.id %>" data-toggle = "modal" data-target = "#Modal-<%= image.id %>">
          <div class="check-box">
            <%= f.check_box :image_ids, {multiple: true}, image.id, false %>
          </div>
          <%= image_tag image.variant(resize_to_fill: [320, 320]) %>
        </div>
        <%= render 'modal', image: image %>
      <% end %>
    </div>
  <% end %>

  <div class="pagination-box">
    <%= will_paginate @images %>
  </div>
<% else %>
  <h2>
    「編集する」より、写真を追加することができます。
  </h2>
<% end %>

<%= render 'detail_map', trip: @trip %>
<%= javascript_pack_tag 'shared/form' %>
<%= javascript_pack_tag 'trips/show' %>